(() => {
  const $=s=>document.querySelector(s); const state=()=>$("#state")?.value||"KA"; const date=()=>$("#date")?.value||new Date().toISOString().slice(0,10); const lat=()=>$("#lat")?.value||"12.9716"; const lon=()=>$("#lon")?.value||"77.5946";
  const labels={hi:{chog:"चौघड़िया",gowri:"गौरी पंचांगम्",good:"शुभ",bad:"अशुभ",access:"अक्षर आकार",month:"क्षेत्रीय माह"},kn:{chog:"ಚೌಘಡಿಯಾ",gowri:"ಗೌರಿ ಪಂಚಾಂಗಂ",good:"ಶುಭ",bad:"ಅಶುಭ",access:"ಅಕ್ಷರ ಗಾತ್ರ",month:"ಪ್ರಾದೇಶಿಕ ತಿಂಗಳು"},ta:{chog:"சௌகடியா",gowri:"கௌரி பஞ்சாங்கம்",good:"நல்லது",bad:"தீயது",access:"எழுத்து அளவு",month:"பிராந்திய மாதம்"},te:{chog:"చౌఘడియా",gowri:"గౌరి పంచాంగం",good:"శుభం",bad:"అశుభం",access:"అక్షర పరిమాణం",month:"ప్రాంతీయ మాసం"},mr:{chog:"चौघडिया",gowri:"गौरी पंचांग",good:"शुभ",bad:"अशुभ",access:"अक्षर आकार",month:"प्रादेशिक महिना"},or:{chog:"ଚୌଘଡ଼ିଆ",gowri:"ଗୌରୀ ପଞ୍ଚାଙ୍ଗ",good:"ଶୁଭ",bad:"ଅଶୁଭ",access:"ଅକ୍ଷର ଆକାର",month:"ଆଞ୍ଚଳିକ ମାସ"},bn:{chog:"চৌঘড়িয়া",gowri:"গৌরী পঞ্জিকা",good:"শুভ",bad:"অশুভ",access:"অক্ষরের আকার",month:"আঞ্চলিক মাস"},as:{chog:"চৌঘড়িয়া",gowri:"গৌৰী পঞ্জিকা",good:"শুভ",bad:"অশুভ",access:"আখৰৰ আকাৰ",month:"আঞ্চলিক মাহ"},pa:{chog:"ਚੌਘੜੀਆ",gowri:"ਗੌਰੀ ਪੰਚਾਂਗ",good:"ਸ਼ੁਭ",bad:"ਅਸ਼ੁਭ",access:"ਅੱਖਰ ਆਕਾਰ",month:"ਖੇਤਰੀ ਮਹੀਨਾ"},gu:{chog:"ચોઘડિયા",gowri:"ગૌરી પંચાંગ",good:"શુભ",bad:"અશુભ",access:"અક્ષર કદ",month:"પ્રાદેશિક મહિનો"},ml:{chog:"ചൗഘഡിയ",gowri:"ഗൗരി പഞ്ചാംഗം",good:"ശുഭം",bad:"അശുഭം",access:"അക്ഷര വലുപ്പം",month:"പ്രാദേശിക മാസം"}};
  const lang=()=>$("#lang")?.value||window.I18N?.stateLang?.[state()]||"hi"; const L=()=>labels[lang()]||labels.hi;
  function applyScale(){const v=Number(localStorage.getItem("panchang-font-scale")||1);document.documentElement.style.setProperty("--font-scale",v);document.body.classList.add("font-scaled");const o=$("#fontScale");if(o)o.value=Math.round(v*100)+"%"}
  function a11y(){if($(".a11y-bar"))return;const d=document.createElement("div");d.className="a11y-bar";d.setAttribute("role","toolbar");d.setAttribute("aria-label",L().access);d.innerHTML='<button type="button" id="fontDown" aria-label="Smaller">A−</button><output id="fontScale">100%</output><button type="button" id="fontUp" aria-label="Larger">A+</button><button type="button" id="fontReset" aria-label="Reset">↺</button>';document.body.appendChild(d);$("#fontDown").onclick=()=>scale(-.1);$("#fontUp").onclick=()=>scale(.1);$("#fontReset").onclick=()=>{localStorage.setItem("panchang-font-scale","1");applyScale()};applyScale()}
  function scale(delta){let v=Number(localStorage.getItem("panchang-font-scale")||1);v=Math.max(.85,Math.min(1.3,Math.round((v+delta)*10)/10));localStorage.setItem("panchang-font-scale",v);applyScale()}
  async function states(){try{const d=await fetch("/api/v1/states").then(r=>r.json());window.__regionalStates=d.states||{};setAccent()}catch(e){}}
  function setAccent(){const c=window.__regionalStates?.[state()];if(c?.accent){document.documentElement.style.setProperty("--state-accent",c.accent);document.body.dataset.stateStyle=c.style||""}}
  async function renderRegional(){const target=$("#r");if(!target)return;try{const q=new URLSearchParams({state_code:state(),lat:lat(),lon:lon(),timezone:"Asia/Kolkata",date_str:date()});const p=await fetch("/api/v1/panchang?"+q).then(r=>r.json());const r=p.regional||{};const slots=r.gowri_panchangam||r.choghadiya_day||[];if(!slots.length)return;const isG=!!r.gowri_panchangam;const title=isG?L().gowri:L().chog;let body='';if(isG){body='<div class="gowri-table">'+slots.map(x=>`<div class="gowri-row ${x.nature.toLowerCase()}"><span class="slot">${x.slot}</span><span class="name">${x.name}</span><span class="time">${x.time}</span><span class="nature">${x.nature==='Good'?L().good:L().bad}</span></div>`).join('')+'</div>'}else{body='<div class="regional-timeline">'+slots.map(x=>`<div class="regional-slot ${x.nature.toLowerCase()}"><div class="n">${x.name}</div><div class="t">${x.time}</div><div class="nature">${x.nature==='Good'?L().good:L().bad}</div></div>`).join('')+'</div>'}const card=document.createElement('section');card.className='regional-card';card.id='regionalMuhurat';card.innerHTML=`<div class="regional-head"><div><div class="regional-title">${title}</div><div class="regional-sub">${r.system||''}</div></div><span class="regional-badge">${isG?'Gowri':'Choghadiya'}</span></div>${body}<div class="regional-priority">${(r.priority_fields||[]).map(x=>`<span>${x.replaceAll('_',' ')}</span>`).join('')}</div>`;target.prepend(card);setAccent()}catch(e){}}
  async function month(){const h=$("#calTitle");if(!h)return;try{const d=new Date(date());const q=new URLSearchParams({state_code:state(),year:String(d.getFullYear()),month:String(d.getMonth()+1),timezone:"Asia/Kolkata"});const x=await fetch('/api/v1/calendar/month?'+q).then(r=>r.json());let m=h.querySelector('.regional-month');if(!m){m=document.createElement('span');m.className='regional-month';h.appendChild(m)}m.textContent=`${L().month}: ${x.regional_month_name||''}`;document.documentElement.style.setProperty('--state-accent',x.regional_accent||getComputedStyle(document.documentElement).getPropertyValue('--state-accent'))}catch(e){}}
  function refresh(){document.querySelector('#regionalMuhurat')?.remove();setAccent();renderRegional();month()}
  document.addEventListener('DOMContentLoaded',()=>{a11y();states();const s=$("#state");if(s)s.addEventListener('change',()=>setTimeout(refresh,250));const mo=new MutationObserver(()=>{if($("#hours")?.children.length){clearTimeout(window.__regionalTimer);window.__regionalTimer=setTimeout(refresh,120)}});const root=$("#dayPanel");if(root)mo.observe(root,{subtree:true,childList:true});setTimeout(refresh,900)});
})();